version: 2.1
orbs:
  heroku: circleci/heroku@0.0.6
jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run: 
          command: |
            heroku run python manage.py makemigrations talenthub
            heroku run python manage.py migrate
      - heroku/deploy-via-git:
  run_tests:
    working_directory: ~/talenthub
    docker:
      - image: circleci/python:3.7.2
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
            command: |
              sudo pip install pipenv
              pipenv install -r requirements.txt
      - run:
          command: |
            pipenv run python manage.py makemigrations
            pipenv run python manage.py migrate
            mkdir test-results
            pipenv run python manage.py test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - run_tests
      - deploy:
          filters: 
            branches:
              only:
                - master
          requires:
            - run_tests