version: 2.1
orbs:
  heroku: circleci/heroku@0.0.6
jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          only-branch: master
  run_tests:
    working_directory: ~/talenthub
    docker:
      - image: circleci/python:3.7.2
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run:
            command: |
              sudo pip install pipenv
              pipenv install -r requirements.txt
      - run:
          command: |
            mkdir test-results
            pipenv run python manage.py test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1

workflows:
  version: 2
  build-deploy:
    jobs:
      - run_tests
      - deploy:
          requires:
            - run_tests