desc = [
"Mathematics teacher at Newtrend International Secondary School .( 2010-2013) Graduate Assistant at Rivers State University of Science and Technology .( 2015-2016) Having been fully grounded with much real-life application of mathematics, my reason of being a maths...",
"September 2015 – January 2018: German University in Cairo (GUC) Teaching Assistant at the Electrical Circuits & Electronics Department English, Calculus 3, CLEP Calculus, CLEP College Algebra, CLEP College Mathematics, College Algebra, Electrical Engineering,...",
"I teach different levels, including: -Pre-intermediate/ intermediate/ upper-intermediate -Pre-advanced/ advanced -Business English in private companies -Exam courses: FCE, CAE, BEC, IELTS -Conversation classes English I have my own English school in Poland where I...",
"3 years of teaching experience . Thermochemistry, AP Environmental Science, AP Physics 1, AP Physics 1 - DUPE, AP Physics 2 - DUPE, AP Physics 2: Electricity and Magnetism, Biology, Calculus 1, Calculus 2, Calculus 3, AP Chemistry, Chemical Engineering, Chemistry, GRE...",
"1996-2002: actor (Literary Theatre) 2002-2004: Logistics Manager (WIF-LAIN Ltd .) 2004-2007: Executive Director (WIF-LAIN Ltd .) 2007-Present: General Director (TLK Ltd .) Russian 1996-2002: actor (Literary Theatre) 2002-2004: Logistics Manager (WIF-LAIN Ltd .) ...",
"Known and recommended for: ● Superb theoretical introduction to the subject ● Explaining the grand picture of each lesson ● Smooth learning process ● Individually-crafted problems and guidance in finding solutions ● Revisions ● Motivation in achieving student's learning..",
"I've been teaching English to students of different ages for 7 years . Over these years I've taught different courses such as General English, Business English, English for Teenagers, Preparation for IELTS exam . I also love learning myself . For this reason in June...",
"Mathematics Teacher, Aligarh Public School, India Private Mathematics Tutor. 9th Grade math, 7th Grade math, 6th Grade math, 5th Grade math, 8th Grade math, 1st Grade math, 2nd Grade math, 3rd Grade math, 4th Grade math, 10th Grade math, 12th Grade math, 11th Grade math...",
"I Have 5 Years Of Experience In Teaching ,I Worked As An Assistant Professor In Engineering College I Was Conducting Tutorial In Bangalore 10th Grade math, 9th Grade math, 12th Grade math, 11th Grade math, 8th Grade math, Computer Science, Computer Programming, Compilers,...",
"I , not only focus on the subjects, but also work on improving students personality traits like confidence building and positive thinking. 7th Grade math, 4th Grade Science, 4th Grade Writing, 5th Grade, 5th Grade math, 5th Grade Reading, 5th Grade Science, 5th Grade Writing,...",
"Diverse experience in concepts and derivations,problems solving tips and tricks etc ... 10th Grade, 10th Grade Reading, 11th Grade, 11th Grade Reading, 12th Grade, 12th Grade math, 10th Grade Writing, 11th Grade Writing, 12th Grade Writing, 12th Grade Reading, 2nd Grade math,...",
"Where ? If you live in Lviv – it can be your place, my place or a café. You can chose any place most comfortable for you . If you don’t live in Lviv we can also have lessons on skype . The only thing you need – is a good, fast internet connection . What do I need to...",
"I've been enjoying teaching German to students of different ages and backgrounds . I lived in Germany for 7 years which gave me the possibility not only to practice the language on a daily basis but also explore and learn to understand German culture and mentality . And this...",
"I want to share my knowledge on world politics and on constantly moving international system . English, Political Science, IB Global Politics SL, IB Global Politics HL, AP U.S. Government & Politics, AP Comparative Government and Politics, World History, History, European...",
"My IELTS score was 7.5/9.0 . GRE score 300/340 . Was the school topper in the Computer Programming Subject scoring 95/100 marks in All India Board exams. Have an experience of tutoring C++ programming for 2.5 years . I've good communication skills and have organised...",
"I can help with various introductory bachelor level subjects connected to language studies such as: Morphology, Syntax, Functional Syntax, Pragmatics, Sociolinguistics (my final thesis from this branch of study) And other introductory level courses, e.g .: Philosophy...",
"I was honored to have my own art exhibitions in my college, as well as my own exhibition in Kiev, the capital of my country, Ukraine . Moreover, I had additional classes of Art during my time in the Humanitarian Gymnasium . Another volunteering experience was teaching...",
"I have extensive experience working at a school with children of different age groups, I was a member of the commission for checking the tasks of the 2 nd stage of the All-Ukrainian Olympiad in Mathematics and tasks with a detailed response to the EIT in the city of...",
"I have always been interested in languages so I keep on studying and improving my language proficiency in English, German, French and Danish . My mother tongue is Ukrainian, I am also fluent in Russian . I will be happy to share my knowledge and help my students to master a..."
]

